on:
  push:
    branches:    
      - master
name: gh-pages docker build
jobs:
  gh-pagesIsMaster:
    name: gh-pages is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: gh-pages docker registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io/cdssnc/gh-pages-github-action
    - name: gh-pages action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: gh-pages/**
    - name: build gh-pages
      run: docker build -t cdssnc/gh-pages-github-action ./gh-pages
    - name: push gh-pages
      run: docker push cdssnc/gh-pages-github-action
